### ISSUE TITLE
depends on both  kartal and http version solving failed

### ISSUE THREAD

**Issue by Adiladil000** [VB10/kartal#36]
![Screenshot 2023-06-09 160137](https://github.com/VB10/kartal/assets/88295387/640064d6-9839-4b8a-8961-aa7cbeb5f8bc)

Hi Veli . Please check this issues

**Comment by VB10** [comment]
yep @Adiladil000 i'll try this and fix it immediately

**Comment by VB10** [comment]
@Adiladil000 i checked this issue, but i could not catch any problem. i test it sample app.

**Comment by zhakypovmaksatbek** [comment]
Hocam bu http ile birlikte kullanamiyorum
hata mesaji:Because no versions of kartal match >2.8.0 <3.0.0 and kartal 2.8.0 depends on package_info_plus ^3.0.2, kartal ^2.8.0 requires package_info_plus ^3.0.2.
And because package_info_plus ^3.0.0 depends on http ^0.13.0, kartal ^2.8.0 requires http ^0.13.0.

**Comment by VB10** [comment]
fixed
